inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/rails/**/*'
    - 'vendor/**/*'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'lib/rspec/openapi/version.rb'
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
