# frozen_string_literal: true

return unless Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('3.0.0')

ENV['TZ'] ||= 'UTC'
ENV['HANAMI_ENV'] ||= 'test'
ENV['OPENAPI_OUTPUT'] ||= 'yaml'

require 'json'
require 'rack/test'

Dir.chdir('spec/apps/hanami') # HACK: for load hanami success
require 'hanami/prepare'

RSpec::OpenAPI.title = 'OpenAPI Documentation'
RSpec::OpenAPI.request_headers = %w[X-Authorization-Token Secret-Key]
RSpec::OpenAPI.response_headers = %w[X-Cursor]
RSpec::OpenAPI.path = File.expand_path("../apps/hanami/doc/openapi.#{ENV.fetch('OPENAPI_OUTPUT', nil)}", __dir__)
RSpec::OpenAPI.ignored_paths = ['/admin/masters/extensions']
RSpec::OpenAPI.comment = <<~COMMENT
  This file is auto-generated by rspec-openapi https://github.com/k0kubun/rspec-openapi

  When you write a spec in spec/requests, running the spec with `OPENAPI=1 rspec` will
  update this file automatically. You can also manually edit this file.
COMMENT
RSpec::OpenAPI.servers = [{ url: 'http://localhost:3000' }]
RSpec::OpenAPI.info = {
  description: 'My beautiful hanami API',
  license: {
    name: 'Apache 2.0',
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html',
  },
}

RSpec::OpenAPI.security_schemes = {
  SecretApiKeyAuth: {
    type: 'apiKey',
    in: 'header',
    name: 'Secret-Key',
  },
}

RSpec.shared_context 'Hanami app' do
  let(:app) { Hanami.app }
end

RSpec.configure do |config|
  config.include Rack::Test::Methods, type: :request
  config.include_context 'Hanami app', type: :request
end

RSpec.describe 'Tables', type: :request do
  describe '#index', openapi: { summary: 'Get a list of tables' } do
    context 'returns a list of tables', openapi: { example_mode: :multiple } do
      it 'with flat query parameters' do
        get '/tables', { page: '1', per: '10' }, { 'AUTHORIZATION' => 'k0kubun', 'X_AUTHORIZATION_TOKEN' => 'token' }
        expect(last_response.status).to eq(200)
      end

      it 'with deep query parameters' do
        get '/tables', { filter: { 'name' => 'Example Table' } }, { 'AUTHORIZATION' => 'k0kubun' }
        expect(last_response.status).to eq(200)
      end

      it 'with different deep query parameters' do
        get '/tables', { filter: { 'price' => 0 } }, { 'AUTHORIZATION' => 'k0kubun' }
        expect(last_response.status).to eq(200)
      end
    end

    # it 'has a request spec which does not make any request' do
    #   expect(last_request).to eq(nil)
    # end
    # Rack::Test::Error:
    #        No request yet. Request a page first.

    it 'does not return tables if unauthorized' do
      get '/tables'
      expect(last_response.status).to eq(401)
    end
  end

  describe '#show' do
    it 'returns a table' do
      get '/tables/1', nil, { 'AUTHORIZATION' => 'k0kubun' }
      expect(last_response.status).to eq(200)
    end

    it 'does not return a table if unauthorized' do
      get '/tables/1'
      expect(last_response.status).to eq(401)
    end

    it 'does not return a table if not found' do
      get '/tables/2', nil, { 'AUTHORIZATION' => 'k0kubun' }
      expect(last_response.status).to eq(404)
    end

    it 'does not return a table if not found (openapi: false)', openapi: false do
      get '/tables/3', nil, { 'AUTHORIZATION' => 'k0kubun' }
      expect(last_response.status).to eq(404)
    end
  end

  describe '#create' do
    it 'returns a table' do
      post '/tables', {
        name: 'k0kubun',
        description: 'description',
        database_id: 2,
      }.to_json,
           { 'AUTHORIZATION' => 'k0kubun', 'CONTENT_TYPE' => 'application/json' }
      expect(last_response.status).to eq(201)
    end

    it 'fails to create a table' do
      post '/tables', {
        description: 'description',
        database_id: 2,
      }.to_json,
           { 'AUTHORIZATION' => 'k0kubun', 'CONTENT_TYPE' => 'application/json' }
      expect(last_response.status).to eq(422)
    end

    it 'fails to create a table (2)' do
      post '/tables', {
        name: 'some_invalid_name',
        description: 'description',
        database_id: 2,
      }.to_json,
           { 'AUTHORIZATION' => 'k0kubun', 'CONTENT_TYPE' => 'application/json' }
      expect(last_response.status).to eq(422)
    end
  end

  describe '#update' do
    it 'returns a table' do
      patch '/tables/1', { name: 'test' },
            { 'AUTHORIZATION' => 'k0kubun', 'CONTENT_TYPE' => 'application/x-www-form-urlencoded' }
      expect(last_response.status).to eq(200)
    end
  end

  describe '#destroy' do
    it 'returns a table' do
      delete '/tables/1', nil, { 'AUTHORIZATION' => 'k0kubun' }
      expect(last_response.status).to eq(200)
    end

    it 'returns no content if specified' do
      delete '/tables/1', { no_content: true },
             { 'AUTHORIZATION' => 'k0kubun', 'CONTENT_TYPE' => 'application/x-www-form-urlencoded' }
      expect(last_response.status).to eq(202)
    end
  end
end

RSpec.describe 'Images', type: :request do
  describe '#payload' do
    it 'returns a image payload' do
      get '/images/1'
      expect(last_response.status).to eq(200)
    end
  end

  describe '#index' do
    it 'can return an object with an attribute of empty array' do
      get '/images'
      expect(last_response.status).to eq(200)
    end
  end

  describe '#upload' do
    before do
      png = 'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAADklEQVQIW2P4DwUMlDEA98A/wTjP
      QBoAAAAASUVORK5CYII='.unpack1('m')
      File.binwrite('test.png', png)
    end
    let(:image) { Rack::Test::UploadedFile.new('test.png', 'image/png') }

    it 'returns a image payload with upload' do
      post '/images/upload', { 'image' => image }
      expect(last_response.status).to eq(200)
    end
  end

  describe '#upload_nested' do
    before do
      png = 'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAADklEQVQIW2P4DwUMlDEA98A/wTjP
      QBoAAAAASUVORK5CYII='.unpack1('m')
      File.binwrite('test.png', png)
    end
    let(:image) { Rack::Test::UploadedFile.new('test.png', 'image/png') }

    it 'returns a image payload with upload nested' do
      post '/images/upload_nested',  { nested_image: { image: image, caption: 'Some caption' } }
      expect(last_response.status).to eq(200)
    end
  end

  describe '#upload_multiple' do
    before do
      png = 'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAADklEQVQIW2P4DwUMlDEA98A/wTjP
      QBoAAAAASUVORK5CYII='.unpack1('m')
      File.binwrite('test.png', png)
    end
    let(:image) { Rack::Test::UploadedFile.new('test.png', 'image/png') }

    it 'returns a image payload with upload multiple' do
      post '/images/upload_multiple', { images: [image, image] }
      expect(last_response.status).to eq(200)
    end
  end

  describe '#upload_multiple_nested' do
    before do
      png = 'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAAAAADhZOFXAAAADklEQVQIW2P4DwUMlDEA98A/wTjP
      QBoAAAAASUVORK5CYII='.unpack1('m')
      File.binwrite('test.png', png)
    end
    let(:image) { Rack::Test::UploadedFile.new('test.png', 'image/png') }

    it 'returns a image payload with upload multiple nested' do
      post '/images/upload_multiple_nested', { images: [{ image: image }, { image: image }] }
      expect(last_response.status).to eq(200)
    end
  end
end

RSpec.describe 'SecretKey securityScheme',
               type: :request,
               openapi: { security: [{ 'SecretApiKeyAuth' => [] }] } do
  describe '#secret_items' do
    it 'authorizes with secret key' do
      get '/secret_items', nil,
          {
            'Secret-Key' => '42',
          }
      expect(last_response.status).to eq(200)
    end
  end
end

RSpec.describe 'Extra routes', type: :request do
  describe '#test_block', openapi: { deprecated: true } do
    it 'returns the block content' do
      get '/test_block'
      expect(last_response.status).to eq(200)
    end
  end
end

RSpec.describe 'Engine test', type: :request do
  describe 'engine routes' do
    it 'returns some content from the engine' do
      get '/my_engine/test'
      expect(last_response.status).to eq(200)
    end
  end
end

RSpec.describe 'Engine extra routes', type: :request do
  describe '#test' do
    it 'returns the block content' do
      get '/my_engine/eng/example'
      expect(last_response.status).to eq(200)
    end
  end
end

RSpec.describe 'Namespace test', type: :request do
  describe '/admin/masters/extensions' do
    it 'returns some content' do
      get '/admin/masters/extensions'
      expect(last_response.status).to eq(200)
    end

    it 'creates a content' do
      post '/admin/masters/extensions'
      expect(last_response.status).to eq(200)
    end
  end
end

RSpec.describe 'Rack app test', type: :request do
  describe '/rack/foo' do
    it 'returns some content foo' do
      get '/rack/foo'
      expect(last_response.status).to eq(200)
    end
  end

  describe '/rack/bar' do
    it 'returns some content bar' do
      get '/rack/bar'
      expect(last_response.status).to eq(200)
    end
  end
end

RSpec.describe 'non-numeric path parameter', type: :request do
  it 'finds a site' do
    get '/sites/abc123'
    expect(last_response.status).to eq(200)
  end

  it 'raises not found' do
    get '/sites/no-such'
    expect(last_response.status).to eq(404)
  end
end

# Tests for example_mode feature (using dedicated test endpoints)

# Test :none mode - should generate only schema, no examples
RSpec.describe 'example_mode :none', type: :request do
  describe 'GET /example_mode_none', openapi: { example_mode: :none } do
    it 'generates schema without example' do
      get '/example_mode_none'
      expect(last_response.status).to eq(200)
    end
  end
end

# Test :single mode (default) - should generate single example
RSpec.describe 'example_mode :single', type: :request do
  describe 'GET /example_mode_single' do
    it 'generates schema with single example' do
      get '/example_mode_single'
      expect(last_response.status).to eq(200)
    end
  end
end

# Test :multiple mode - should generate named examples
RSpec.describe 'example_mode :multiple', type: :request do
  describe 'GET /example_mode_multiple', openapi: { example_mode: :multiple } do
    it 'first example' do
      get '/example_mode_multiple'
      expect(last_response.status).to eq(200)
    end

    it 'second example' do
      get '/example_mode_multiple'
      expect(last_response.status).to eq(200)
    end
  end
end

# Test inheritance - parent sets :multiple, children inherit
RSpec.describe 'example_mode inheritance', type: :request, openapi: { example_mode: :multiple } do
  describe 'GET /example_mode_inherit' do
    # This test inherits :multiple from parent RSpec.describe
    it 'inherits multiple from parent' do
      get '/example_mode_inherit'
      expect(last_response.status).to eq(200)
    end

    it 'also inherits multiple from parent' do
      get '/example_mode_inherit'
      expect(last_response.status).to eq(200)
    end
  end

  # Test override to :single within :multiple context
  describe 'GET /example_mode_override_single', openapi: { example_mode: :single } do
    it 'overrides to single' do
      get '/example_mode_override_single'
      expect(last_response.status).to eq(200)
    end
  end

  # Test override to :none within :multiple context
  describe 'GET /example_mode_override_none', openapi: { example_mode: :none } do
    it 'overrides to none' do
      get '/example_mode_override_none'
      expect(last_response.status).to eq(200)
    end
  end
end

# Test mixed example modes on same endpoint (merger conversion test)
# First test with :single (example), second test with :multiple (examples)
# Merger should convert :single to examples when mixed
RSpec.describe 'example_mode mixed', type: :request do
  describe 'GET /example_mode_mixed' do
    # First test with :single (default) - will be converted to examples by merger
    it 'first with single mode' do
      get '/example_mode_mixed'
      expect(last_response.status).to eq(200)
    end

    # Second test with :multiple - merger should convert the first to examples
    context 'with multiple', openapi: { example_mode: :multiple } do
      it 'second with multiple mode' do
        get '/example_mode_mixed'
        expect(last_response.status).to eq(200)
      end
    end
  end
end

# Test global enable_example = false overrides example_mode
RSpec.describe 'example_mode disabled globally', type: :request do
  before(:context) do
    @original_enable_example = RSpec::OpenAPI.enable_example
    RSpec::OpenAPI.enable_example = false
  end

  after(:context) do
    RSpec::OpenAPI.enable_example = @original_enable_example
  end

  describe 'GET /example_mode_disabled' do
    it 'does not generate examples for default mode' do
      get '/example_mode_disabled'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'GET /example_mode_disabled_single', openapi: { example_mode: :single } do
    it 'does not generate examples for single mode' do
      get '/example_mode_disabled_single'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'GET /example_mode_disabled_multiple', openapi: { example_mode: :multiple } do
    it 'does not generate examples for multiple mode' do
      get '/example_mode_disabled_multiple'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'GET /example_mode_disabled_none', openapi: { example_mode: :none } do
    it 'does not generate examples for none mode' do
      get '/example_mode_disabled_none'
      expect(last_response.status).to eq(200)
    end
  end
end

RSpec.describe 'Array of hashes', type: :request do
  describe 'with nullable keys' do
    it 'returns some content' do
      get '/array_hashes/nullable'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with non-nullable keys' do
    it 'returns some content' do
      get '/array_hashes/non_nullable'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with nullable keys' do
    it 'returns some content' do
      get '/array_hashes/nullable'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with nested keys with type conflicts' do
    it 'returns some content' do
      get '/array_hashes/nested'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with empty array' do
    it 'returns empty items' do
      get '/array_hashes/empty_array'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with single item' do
    it 'returns single item' do
      get '/array_hashes/single_item'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with non-hash items' do
    it 'returns array of strings' do
      get '/array_hashes/non_hash_items'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with nested arrays' do
    it 'returns items with array properties' do
      get '/array_hashes/nested_arrays'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with nested objects' do
    it 'returns items with object properties' do
      get '/array_hashes/nested_objects'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with mixed types in nested objects' do
    it 'returns items with type conflicts in nested properties' do
      get '/array_hashes/mixed_types_nested'
      expect(last_response.status).to eq(200)
    end
  end

  describe 'with mixed types in nested objects in nested array' do
    it 'returns items that would produce different oneOf types' do
      get '/array_hashes/multiple_one_of_test'
      expect(last_response.status).to eq(200)
    end
  end
end
