# frozen_string_literal: true

ENV['TZ'] ||= 'UTC'
ENV['RAILS_ENV'] ||= 'test'
ENV['OPENAPI_OUTPUT'] ||= 'yaml'

require File.expand_path('../apps/rails/config/environment', __dir__)
require 'rspec/rails'

RSpec::OpenAPI.path = File.expand_path(
  "../apps/rails/doc/description_preserve/openapi.#{ENV.fetch('OPENAPI_OUTPUT', nil)}", __dir__,
)
RSpec::OpenAPI.comment = <<~COMMENT
  This file is auto-generated by rspec-openapi https://github.com/k0kubun/rspec-openapi
COMMENT
RSpec::OpenAPI.servers = [{ url: 'http://localhost:3000' }]

# Test that example_mode :none does NOT overwrite an existing description
RSpec.describe 'Description preservation', type: :request do
  describe 'GET /description_preserve_test', openapi: { example_mode: :none } do
    it 'should not overwrite the existing description' do
      get '/description_preserve_test'
      expect(response.status).to eq(200)
    end
  end

  # Test that normal mode DOES overwrite an existing description
  describe 'GET /description_overwrite_test' do
    it 'new description from test' do
      get '/description_overwrite_test'
      expect(response.status).to eq(200)
    end
  end

  # The exact scenario from #318: same endpoint hit by BOTH a documented test
  # and an example_mode: :none test. The documented description must win
  # regardless of RSpec's random execution order.
  describe 'GET /description_mixed_test' do
    context 'with example_mode :none', openapi: { example_mode: :none } do
      it 'should not win description' do
        get '/description_mixed_test'
        expect(response.status).to eq(200)
      end
    end

    context 'documented' do
      it 'documented description wins' do
        get '/description_mixed_test'
        expect(response.status).to eq(200)
      end
    end
  end
end
