ENV['TZ'] ||= 'UTC'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('rails/config/environment', __dir__)
require 'rspec/rails'

RSpec::OpenAPI.path = File.expand_path('rails/doc/openapi.yaml', __dir__)
RSpec::OpenAPI.comment = <<~EOS
  This file is auto-generated by rspec-openapi https://github.com/k0kubun/rspec-openapi

  When you write a spec in spec/requests, running the spec with `OPENAPI=1 rspec` will
  update this file automatically. You can also manually edit this file.
EOS
